# Modified from: https://github.com/choldgraf/deploy_configurations/blob/master/.github/workflows/main.yml
# Note: lint with https://rhysd.github.io/actionlint/
name: Publish JupyterBook to GitHub Pages

on: 
  push: # trigger build only when push to master
    branches:
      - main
      - test-gh-actions # GH actions test branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        pip install numpy
        pip install sympy
        pip install matplotlib
        pip install jupyter-book
        pip install ghp-import
        PATH="${PATH}:${HOME}/.local/bin"

    - name: Build book HTML 
      run: |
        jupyter-book build ./book

    - name: Push built book HTML as artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "book/_build/html"

    - name: Deploy book HTML to Github Pages
      id: deployment
      uses: actions/deploy-pages@v2

    - name: Build PDF of book
      run: |
        sudo apt-get update
        sudo apt-get install texlive-latex-extra \
                             texlive-fonts-extra \
                             texlive-xetex latexmk
        # Build actual book
        jupyter-book build book --builder pdflatex
        mv book/_build/latex/python.pdf book/_build/elara-handbook.pdf

    - name: Upload book PDF to Github releases
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        pip install github-release-retry
        github-release-retry \
          --user elaraproject \
          --repo elara-handbook \
          --tag_name v0.0.0-$(git rev-parse HEAD | cut -c 1-8) \
          --prerelease \
          --body_string "Automatically generated from book sources via Github Actions" \
          book/_build/elara-handbook.pdf
